name: Prettier formatting
on: [push, pull_request]

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Validate formatting
        run: yarn --silent test:format
